using System;
using System.Collections.Generic;
using System.Web.UI;

public partial class Aspx_SignUp : System.Web.UI.Page
{
    BackEnd backEnd = new BackEnd();

    protected void Page_Load(object sender, EventArgs e)
    {
        //Hide navigation bar options because on sign up
        foreach (LiteralControl a in Master.FindControl("navigationbar").Controls)
        {
            a.Visible = false;
        }
    }

    protected void signUpButtonClicked(object sender, EventArgs e)
    {
        //Read form attributes into user object
        User newUser = new User();
        foreach (TableAttribute attribute in newUser.GetTableAttributes())
        {
            string value = Request.Form["ctl00$Main_Content_Placeholder$" + attribute.id];
            if(value != null)
            {
                if (!newUser.setAttributeValue(attribute.id, value))
                {
                    Errors.InnerText = "Database error! Code #2201";
                    return;
                }
            }
            
        }

        //add unique ID for user
        string newUserID = backEnd._storage.generateUniqueUserID();
        if (!newUser.setAttributeValue("id", newUserID))
        {
            Errors.InnerText = "Database error! Code #2202";
            return;
        }


        //any other attributes generated by code should go here
        if (!newUser.setAttributeValue("logged_in", "false") ||
            !newUser.setAttributeValue("rating", Globals.NewUsersRating)
            )
        {
            Errors.InnerText = "Database error! Code #2203";
            return;
        }

        //Validation
        string inputValidationErrors = backEnd._inputValiddation.validateUser(newUser);
        if (inputValidationErrors != "SUCCESS")
        {
            Errors.InnerText = "**Error message, todo improve**** :" + inputValidationErrors;
            return;
        }

        //check if user already exists
        if (backEnd._storage.doesNameExist(newUser.getAttribute("name")))
        {
            Errors.InnerText = "User already exists!";
            return;
        }

        //If validated, send new user to database 
        if(!newUser.insertIntoDatabase())
        {
            Errors.InnerText = "Database error! Code #2210";
            return;
        }

        if (!backEnd._storage.loginUser(newUserID))
        {
            Errors.InnerText = "Database error! Code #2211";
            return;
        }

        //Send email verification
        backEnd._helpfullFunctions.sendVerificationEmail(newUser);

        //save currentUserID
        Session["currentUserID"] = newUserID;

        //navigate to homePage
        Response.Redirect("../Navigation/Home.aspx");
    }
}
